version: '3.8'

services:
  app:
    build: .
    container_name: guest_service_app
    networks:
      - guest_network
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: guest_service_db
    networks:
      - guest_network
    environment:
      POSTGRES_DB: guest_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  guest_network: